export const dictionnaire: Record<string, Record<string, string>> = {
    en: {
        app_subtitle: "Focus & Productivity",
        input_placeholder: "What's next ?",
        btn_add: "Add",
        btn_logout: "Logout",
        menu_rename: "Rename",
        menu_delete: "Delete",
        settings_title: "Settings",
        settings_account: "Account",
        settings_logged_as: "Logged in as ",
        settings_display: "Display",
        settings_show_general: "Show the 'General' list",
        settings_language: "Language",
        settings_select_lang: "Select a language",
        btn_theme: "Theme",
        btn_settings: "Settings",

        settings_dark: "Dark",
        settings_light: "Light",
        settings_email: "Email",
        settings_username: "Username",
        settings_password: "Password",
        settings_theme: "Theme",
        btn_save: "Save",

        feedback_username_empty: "Field is empty",
        feedback_username_same: "Same as current",
        feedback_password_empty: "Both fields are required",
        feedback_password_weak: "8 chars min, 1 uppercase, 1 lowercase, 1 digit",
        feedback_unauthorized: "Session expired, please log in again",
        feedback_database_error: "A server error occurred, please try again",
        feedback_username_required: "Username is required",
        feedback_username_too_long: "Username must be 255 characters or less",
        feedback_username_updated: "Username updated",
        feedback_password_required: "Both fields are required",
        feedback_password_too_short: "Password must be at least 8 characters",
        feedback_password_no_uppercase: "Password must contain at least one uppercase letter",
        feedback_password_no_lowercase: "Password must contain at least one lowercase letter",
        feedback_password_no_digit: "Password must contain at least one digit",
        feedback_password_wrong_old: "Current password is incorrect",
        feedback_password_updated: "Password updated",
        feedback_login_missing_fields: "Email and password are required",
        feedback_login_invalid_credentials: "Incorrect email or password",
        feedback_login_success: "Login successful",
        feedback_register_missing_fields: "All fields are required",
        feedback_register_invalid_email: "Invalid email format",
        feedback_register_email_taken: "This email is already registered",
        feedback_register_success: "Account created, you can now log in",
    },
    fr: {
        app_subtitle: "Focus & Productivité",
        input_placeholder: "Quelle est la suite ?",
        btn_add: "Ajouter",
        btn_logout: "Déconnexion",
        menu_rename: "Renommer",
        menu_delete: "Supprimer",
        settings_title: "Paramètres",
        settings_account: "Compte",
        settings_language: "Langue",
        settings_logged_as: "Connecté en tant que ",
        settings_display: "Affichage",
        settings_show_general: "Afficher la liste 'Général'",
        settings_select_lang: "Sélectionnez une langue",
        btn_theme: "Thème",
        btn_settings: "Paramètres",
        
        settings_dark: "Sombre",
        settings_light: "Clair",
        settings_email: "Email",
        settings_username: "Nom d'utilisateur",
        settings_password: "Mot de passe",
        settings_theme: "Thème",
        btn_save: "Enregistrer",

        feedback_username_empty: "Le champ est vide",
        feedback_username_same: "Identique à l'actuel",
        feedback_password_empty: "Les deux champs sont requis",
        feedback_password_weak: "8 caractères min, 1 majuscule, 1 minuscule, 1 chiffre",
        feedback_unauthorized: "Session expirée, veuillez vous reconnecter",
        feedback_database_error: "Une erreur serveur est survenue, veuillez réessayer",
        feedback_username_required: "Le nom d'utilisateur est requis",
        feedback_username_too_long: "Le nom d'utilisateur ne peut pas dépasser 255 caractères",
        feedback_username_updated: "Nom d'utilisateur mis à jour",
        feedback_password_required: "Les deux champs sont requis",
        feedback_password_too_short: "Le mot de passe doit contenir au moins 8 caractères",
        feedback_password_no_uppercase: "Le mot de passe doit contenir au moins une majuscule",
        feedback_password_no_lowercase: "Le mot de passe doit contenir au moins une minuscule",
        feedback_password_no_digit: "Le mot de passe doit contenir au moins un chiffre",
        feedback_password_wrong_old: "Ancien mot de passe incorrect",
        feedback_password_updated: "Mot de passe mis à jour",
        feedback_login_missing_fields: "Email et mot de passe requis",
        feedback_login_invalid_credentials: "Email ou mot de passe incorrect",
        feedback_login_success: "Connexion réussie",
        feedback_register_missing_fields: "Tous les champs sont requis",
        feedback_register_invalid_email: "Format d'email invalide",
        feedback_register_email_taken: "Cet email est déjà utilisé",
        feedback_register_success: "Compte créé, vous pouvez maintenant vous connecter",
    }
};

// Global variable to store the active language, initialized from localStorage or defaulting to 'en'
export let langueActive: string = localStorage.getItem('langue') || 'en';