export const dictionnaire: Record<string, Record<string, string>> = {
    en: {
        app_subtitle: "Focus & Productivity",
        input_placeholder: "What's next ?",
        btn_add: "Add",
        btn_logout: "Logout",
        menu_rename: "Rename",
        menu_delete: "Delete",
        settings_title: "Settings",
        settings_account: "Account",
        settings_logged_as: "Logged in as ",
        settings_display: "Display",
        settings_show_general: "Show the 'General' list",
        settings_language: "Language",
        settings_select_lang: "Select a language",
        btn_theme: "Theme",
        btn_settings: "Settings",

        settings_dark: "Dark",
        settings_light: "Light",
        settings_email: "Email",
        settings_username: "Username",
        settings_password: "Password",
        settings_theme: "Theme",
        btn_save: "Save",
        feedback_username_success: "Username updated",
        feedback_username_empty: "Field is empty",
        feedback_username_same: "Same as current",
        feedback_password_success: "Password updated",
        feedback_password_empty: "Both fields are required",
        feedback_password_weak: "8 chars min, 1 uppercase, 1 lowercase, 1 digit",
    },
    fr: {
        app_subtitle: "Focus & Productivité",
        input_placeholder: "Quelle est la suite ?",
        btn_add: "Ajouter",
        btn_logout: "Déconnexion",
        menu_rename: "Renommer",
        menu_delete: "Supprimer",
        settings_title: "Paramètres",
        settings_account: "Compte",
        settings_language: "Langue",
        settings_logged_as: "Connecté en tant que ",
        settings_display: "Affichage",
        settings_show_general: "Afficher la liste 'Général'",
        settings_select_lang: "Sélectionnez une langue",
        btn_theme: "Thème",
        btn_settings: "Paramètres",
        
        settings_dark: "Sombre",
        settings_light: "Clair",
        settings_email: "Email",
        settings_username: "Nom d'utilisateur",
        settings_password: "Mot de passe",
        settings_theme: "Thème",
        btn_save: "Enregistrer",
        feedback_username_success: "Nom d'utilisateur mis à jour",
        feedback_username_empty: "Le champ est vide",
        feedback_username_same: "Identique à l'actuel",
        feedback_password_success: "Mot de passe mis à jour",
        feedback_password_empty: "Les deux champs sont requis",
        feedback_password_weak: "8 caractères min, 1 majuscule, 1 minuscule, 1 chiffre",
    }
};

// Global variable to store the active language, initialized from localStorage or defaulting to 'en'
export let langueActive: string = localStorage.getItem('langue') || 'en';